### ISSUE TITLE
ui建议

### ISSUE THREAD

**Issue by hoayo** [Charles7c/charles7c.github.io#56]
建议插入图片使用圆角样式

**Comment by Charles7c** [comment]
> 建议插入图片使用圆角样式

我刚才去看了看掘金、CSDN、简书，目前它们的图片普遍是直角样式，不过圆角也确实会更柔和一些，有需要的话可以在 `docs/.vitepress/theme/styles/custom.css` 中添加这段样式代码。

``` css
.VPDoc .content-container img {
  border-radius: 5px;
}
```

![image](https://user-images.githubusercontent.com/25446948/190682069-0fdbd612-f225-43a4-858c-2f025bbdc87f.png)
